-- 修复表注释的字符集问题
ALTER TABLE vintage_order COMMENT '古着订单表';

-- 如果需要，也可以修复字段注释
ALTER TABLE vintage_order
MODIFY COLUMN order_id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '订单ID',
MODIFY COLUMN order_code VARCHAR(32) NOT NULL COMMENT '订单编码',
MODIFY COLUMN douyin_username VARCHAR(50) NOT NULL COMMENT '抖音用户名',
MODIFY COLUMN recipient_name VARCHAR(50) NOT NULL COMMENT '收货人姓名',
MODIFY COLUMN price DECIMAL(10, 2) NOT NULL COMMENT '商品价格',
MODIFY COLUMN address VARCHAR(200) NOT NULL COMMENT '收货地址',
MODIFY COLUMN create_by VARCHAR(64) DEFAULT '' COMMENT '创建者',
MODIFY COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
MODIFY COLUMN update_by VARCHAR(64) DEFAULT '' COMMENT '更新者',
MODIFY COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
MODIFY COLUMN del_flag CHAR(1) DEFAULT '0' COMMENT '删除标志（0存在 2删除）';
